services:
  # Web Service
  - type: web
    name: weekly-hour-calculator
    runtime: python
    buildCommand: |
      npm install
      npm run build
      pip install -r backend/requirements.txt
      python backend/manage.py migrate --noinput
      python backend/manage.py create_default_superuser
    startCommand: python backend/manage.py collectstatic --noinput && cd backend && gunicorn timetracker.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: changeme123
      - key: DATABASE_URL
        fromDatabase:
          name: weekly-hour-calculator-db
          property: connectionString
    healthCheckPath: /
    
databases:
  # PostgreSQL Database
  - name: weekly-hour-calculator-db
    databaseName: weekly_hour_calculator
    plan: free
